

INSERT INTO `utilisateur` (`id_utilisateur`, `taille`, `poid`, `age`, `localisation`, `cheveux_couleur`, `cheveux_coupe`, `mail`, `nom`, `photos_ref`, `nationnalite`, `profession`, `hobbies`, `attentes`, `couleur_yeux`, `origine`, `signe_distinct`, `Style_vestimentaire`, `style_de_vie`, `personalitees`, `tabac_addict`, `alcool_addict`, `je_vie`, `je_sors`, `activite_sport`, `musique`, `cinema`, `livre`, `magazine_journaux`, `mot_de_pass`, `login`, `mail_interne`) VALUES
(1, 170, 65, 28, 'Vincenne', 'blond', 'court', 'yo@gmail.com', 'mik', NULL, 'Française', 'Dev web', 'tester les applications de Mars qui ne fonctionnent pas', 'que ça fonctionne', 'bleu', 'européen', 'Barbe, trace de sang', 'troué de coup de couteau', 'sanglante', 'abject', 'jamais', 'récement', 'sous les toits', 'difficilement', 'aucune', 'la mélodie de la mort', 'l''horreur', 'Hannibal', 'comment tuer son boss', 'thom', 'mika', ''),
(1000000001, 180, 70, 23, 'Paris', 'Brun', 'Long', 'bakumtsu20@gmail.com', 'Danger', NULL, 'Française', 'Dev web', 'Boire du rhum, du champagne, manger dormir faire la fête.', 'Rien a part une personne de plus pour me filer un coup de main sur le site', 'maron', 'européen', 'tatouage, cicatrice, marque de morsure, de brulure, UN GUERRIER QUOI', 'A poil', 'comme je suis', 'complexe', 'assez', 'a mort', 'sous les ponts', 'jamais de mon carton', 'ecrire', 'Quand la musique est bonne', 'Totoro', 'Le silence des agneaux', 'comment dépecer facile', 'thomas', 'Mars', ''),
(1000000002, 200, 100, 78, 'PANAME', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'aa', 'thom', ''),
(1000000003, NULL, NULL, NULL, NULL, NULL, NULL, 'bb@free.fr', 'guivarch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'mot', 'connard', ''),
(1000000004, NULL, NULL, NULL, NULL, NULL, NULL, 'a@free.fr', 'dan', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'thom', 'th', ''),
(1000000005, NULL, NULL, NULL, NULL, NULL, NULL, 'bla@free.fr', 'bloup', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'b', 'blabla', '');
